@php
    $vessel = $vessel ?? null;
    $user = auth()->user();
    $systemName = config('app.name', 'Vessel Management System');
    $generatedAt = now()->format('d/m/Y H:i');
@endphp

<div style="padding-bottom: 8px; margin-bottom: 0;">
    <table style="width: 100%; border: none; border-collapse: collapse;">
        <tr>
            <td style="width: 60%; vertical-align: top; border: none; padding: 0;">
                <h1 style="color: #2563eb; font-size: 18px; margin: 0 0 6px 0; font-weight: bold; line-height: 1.2; letter-spacing: 0.02em;">
                    {{ $systemName }}
                </h1>
                <p style="color: #000; font-size: 9px; margin: 0; line-height: 1.4; letter-spacing: 0.02em;">
                    @if($vessel)
                        <strong>Vessel:</strong> {{ $vessel->name }}<br>
                        @if($vessel->registration_number)
                            <strong>Registration:</strong> {{ $vessel->registration_number }}<br>
                        @endif
                        @if($vessel->vessel_type)
                            <strong>Type:</strong> {{ $vessel->vessel_type }}
                        @endif
                    @else
                        System Report
                    @endif
                </p>
            </td>
            <td style="width: 40%; vertical-align: top; text-align: right; border: none; padding: 0;">
                <div style="background-color: #f8f9fa; padding: 10px; border-radius: 4px; border: 1px solid #e0e0e0; display: inline-block;">
                    <p style="margin: 0; font-size: 8px; color: #000; line-height: 1.4; text-align: left; letter-spacing: 0.02em;">
                        <strong>Generated:</strong> {{ $generatedAt }}<br>
                        @if($user)
                            <strong>Generated by:</strong> {{ $user->name }}<br>
                            <strong>Email:</strong> {{ $user->email }}
                        @endif
                    </p>
                </div>
            </td>
        </tr>
    </table>
</div>

@if(isset($title) && $title)
    <div style="margin-top: 8px; margin-bottom: 8px;">
        <h2 style="color: #000; font-size: 16px; font-weight: bold; margin: 0 0 4px 0; padding: 0; letter-spacing: 0.02em; line-height: 1.2;">
            {{ $title }}
        </h2>
        @if(isset($subtitle) && $subtitle)
            <p style="color: #000; font-size: 11px; margin: 0; line-height: 1.3; letter-spacing: 0.02em;">
                {{ $subtitle }}
            </p>
        @endif
    </div>
@endif

