<?php

return [
    // Report titles
    'Transaction Report'                             => 'Transaction Report',
    'Movements and Transactions Overview'            => 'Movements and Transactions Overview',
    'All Transactions'                               => 'All Transactions',

    // Section headers
    'Period:'                                        => 'Period:',
    'Summary'                                        => 'Summary',
    'Transactions'                                   => 'Transactions',

    // Summary labels
    'Total Income'                                   => 'Total Income',
    'Total Expenses'                                 => 'Total Expenses',
    'Net Balance'                                    => 'Net Balance',
    'Total Transactions'                             => 'Total Transactions',

    // Table headers
    'Date'                                           => 'Date',
    'Description'                                    => 'Description',
    'Category'                                       => 'Category',
    'Amount'                                         => 'Amount',
    'Type'                                           => 'Type',

    // Empty state
    'No transactions found for the selected period.' => 'No transactions found for the selected period.',

    // Transaction types
    'Income'                                         => 'Income',
    'Expense'                                        => 'Expense',
    'Transfer'                                       => 'Transfer',

    // Header/Footer labels
    'Vessel:'                                        => 'Vessel:',
    'Registration:'                                  => 'Registration:',
    'Type:'                                          => 'Type:',
    'Generated:'                                     => 'Generated:',
    'Generated by:'                                  => 'Generated by:',
    'Email:'                                         => 'Email:',
    'Page :pageNumber of :pageCount'                 => 'Page :pageNumber of :pageCount',
    'Generated on'                                   => 'Generated on',
    'All rights reserved'                            => 'All rights reserved',
];
