<?php

return [
    // Report titles
    'Transaction Report'                             => 'Rapport de Transactions',
    'Movements and Transactions Overview'            => 'Aperçu des Mouvements et Transactions',
    'All Transactions'                               => 'Toutes les Transactions',

    // Section headers
    'Period:'                                        => 'Période:',
    'Summary'                                        => 'Résumé',
    'Transactions'                                   => 'Transactions',

    // Summary labels
    'Total Income'                                   => 'Total des Revenus',
    'Total Expenses'                                 => 'Total des Dépenses',
    'Expense'                                        => 'Dépense',
    'Net Balance'                                    => 'Solde Net',
    'Total Transactions'                             => 'Total des Transactions',

    // Table headers
    'Date'                                           => 'Date',
    'Description'                                    => 'Description',
    'Category'                                       => 'Catégorie',
    'Amount'                                         => 'Montant',
    'Type'                                           => 'Type',

    // Empty state
    'No transactions found for the selected period.' => 'Aucune transaction trouvée pour la période sélectionnée.',

    // Transaction types
    'Income'                                         => 'Revenu',
    'Expense'                                        => 'Dépense',
    'Transfer'                                       => 'Transfert',

    // Header/Footer labels
    'Vessel:'                                        => 'Navire:',
    'Registration:'                                  => 'Immatriculation:',
    'Type:'                                          => 'Type:',
    'Generated:'                                     => 'Généré:',
    'Generated by:'                                  => 'Généré par:',
    'Email:'                                         => 'E-mail:',
    'Page :pageNumber of :pageCount'                 => 'Page :pageNumber sur :pageCount',
    'Generated on'                                   => 'Généré le',
    'All rights reserved'                            => 'Tous droits réservés',

    // Marea Report
    'Marea Report'                                   => 'Rapport de Marea',
    'Fishing Trip Overview'                          => 'Aperçu du Voyage de Pêche',
    'Marea Information'                              => 'Informations sur la Marea',
    'Marea Number'                                   => 'Numéro de Marea',
    'Status'                                         => 'Statut',
    'Name'                                           => 'Nom',
    'Dates'                                          => 'Dates',
    'Estimated Departure'                            => 'Départ Estimé',
    'Actual Departure'                               => 'Départ Réel',
    'Estimated Return'                               => 'Retour Estimé',
    'Actual Return'                                  => 'Retour Réel',
    'Net Result'                                     => 'Résultat Net',
    'Distribution Calculation'                       => 'Calcul de Distribution',
    'Item'                                           => 'Article',
    'Value'                                          => 'Valeur',
    'Final Result'                                   => 'Résultat Final',
    'Income Transactions'                            => 'Transactions de Revenus',
    'Expense Transactions'                           => 'Transactions de Dépenses',
    'Crew Members'                                   => 'Membres de l\'Équipage',
    'Crew Member'                                    => 'Membre de l\'Équipage',
    'Salary Payments'                                => 'Paiements de Salaire',
    'Total Salary Payments'                          => 'Total des Paiements de Salaire',
    'Fishing Quantity Returns'                       => 'Retours de Quantité de Pêche',

    // Maintenance Report
    'Maintenance Report'                             => 'Rapport de Maintenance',
    'Maintenance Overview'                           => 'Aperçu de la Maintenance',
    'Maintenance Information'                        => 'Informations de Maintenance',
    'Maintenance Number'                             => 'Numéro de Maintenance',
    'Start Date'                                     => 'Date de Début',
    'End Date'                                       => 'Date de Fin',
    'Closed At'                                      => 'Fermé Le',
    'Open'                                           => 'Ouvert',
    'Closed'                                         => 'Fermé',
    'Cancelled'                                      => 'Annulé',
    'No transactions found for this maintenance.'    => 'Aucune transaction trouvée pour cette maintenance.',
    'Quantity'                                       => 'Quantité',
    'Notes'                                          => 'Notes',
    'transactions'                                   => 'transactions',
    'Preparing'                                      => 'Préparation',
    'At Sea'                                         => 'En Mer',
    'Returned'                                       => 'Retourné',
    'Closed'                                         => 'Fermé',
    'Cancelled'                                      => 'Annulé',

    // Financial Report
    'Financial Report'                               => 'Rapport Financier',
    'Comprehensive financial overview for'           => 'Aperçu financier complet pour',
    'Category Breakdown'                             => 'Répartition par Catégorie',
    'Expenses by Category'                           => 'Dépenses par Catégorie',
    'Income by Category'                             => 'Revenus par Catégorie',
    'Daily Breakdown'                                => 'Répartition Quotidienne',
    'Mareas (Fishing Trips)'                         => 'Mareas (Voyages de Pêche)',
    'Percentage'                                     => 'Pourcentage',
    'Count'                                          => 'Nombre',
    'Net'                                            => 'Net',
    'Quantity Returns'                               => 'Retours de Quantité',
    'Uncategorized'                                  => 'Sans Catégorie',

    // VAT Report
    'VAT Report'                                     => 'Rapport de TVA',
    'Comprehensive VAT overview for'                 => 'Aperçu complet de la TVA pour',
    'Total VAT'                                      => 'Total TVA',
    'Base Amount'                                    => 'Montant de Base',
    'Total with VAT'                                 => 'Total avec TVA',
    'VAT by Profile'                                 => 'TVA par Profil',
    'VAT by Category'                                => 'TVA par Catégorie',
    'Daily VAT Breakdown'                            => 'Répartition Quotidienne de la TVA',
    'VAT by Marea'                                   => 'TVA par Marea',
    'All Transactions with VAT'                      => 'Toutes les Transactions avec TVA',
    'VAT Profile'                                    => 'Profil de TVA',
    'VAT'                                            => 'TVA',
    'Total'                                          => 'Total',
    'Unknown'                                        => 'Inconnu',
];
