<?php

return [
    // Report titles
    'Transaction Report'                             => 'Rapport de Transactions',
    'Movements and Transactions Overview'            => 'Aperçu des Mouvements et Transactions',
    'All Transactions'                               => 'Toutes les Transactions',

    // Section headers
    'Period:'                                        => 'Période:',
    'Summary'                                        => 'Résumé',
    'Transactions'                                   => 'Transactions',

    // Summary labels
    'Total Income'                                   => 'Total des Revenus',
    'Total Expenses'                                 => 'Total des Dépenses',
    'Net Balance'                                    => 'Solde Net',
    'Total Transactions'                             => 'Total des Transactions',

    // Table headers
    'Date'                                           => 'Date',
    'Description'                                    => 'Description',
    'Category'                                       => 'Catégorie',
    'Amount'                                         => 'Montant',
    'Type'                                           => 'Type',

    // Empty state
    'No transactions found for the selected period.' => 'Aucune transaction trouvée pour la période sélectionnée.',

    // Transaction types
    'Income'                                         => 'Revenu',
    'Expense'                                        => 'Dépense',
    'Transfer'                                       => 'Transfert',

    // Header/Footer labels
    'Vessel:'                                        => 'Navire:',
    'Registration:'                                  => 'Immatriculation:',
    'Type:'                                          => 'Type:',
    'Generated:'                                     => 'Généré:',
    'Generated by:'                                  => 'Généré par:',
    'Email:'                                         => 'E-mail:',
    'Page :pageNumber of :pageCount'                 => 'Page :pageNumber sur :pageCount',
    'Generated on'                                   => 'Généré le',
    'All rights reserved'                            => 'Tous droits réservés',
];
