<?php

return [
    // Report titles
    'Transaction Report'                             => 'Informe de Transacciones',
    'Movements and Transactions Overview'            => 'Resumen de Movimientos y Transacciones',
    'All Transactions'                               => 'Todas las Transacciones',

    // Section headers
    'Period:'                                        => 'Período:',
    'Summary'                                        => 'Resumen',
    'Transactions'                                   => 'Transacciones',

    // Summary labels
    'Total Income'                                   => 'Total de Ingresos',
    'Total Expenses'                                 => 'Total de Gastos',
    'Net Balance'                                    => 'Saldo Neto',
    'Total Transactions'                             => 'Total de Transacciones',

    // Table headers
    'Date'                                           => 'Fecha',
    'Description'                                    => 'Descripción',
    'Category'                                       => 'Categoría',
    'Amount'                                         => 'Importe',
    'Type'                                           => 'Tipo',

    // Empty state
    'No transactions found for the selected period.' => 'No se encontraron transacciones para el período seleccionado.',

    // Transaction types
    'Income'                                         => 'Ingreso',
    'Expense'                                        => 'Gasto',
    'Transfer'                                       => 'Transferencia',

    // Header/Footer labels
    'Vessel:'                                        => 'Embarcación:',
    'Registration:'                                  => 'Registro:',
    'Type:'                                          => 'Tipo:',
    'Generated:'                                     => 'Generado:',
    'Generated by:'                                  => 'Generado por:',
    'Email:'                                         => 'Correo electrónico:',
    'Page :pageNumber of :pageCount'                 => 'Página :pageNumber de :pageCount',
    'Generated on'                                   => 'Generado el',
    'All rights reserved'                            => 'Todos los derechos reservados',
];
