<?php

return [
    // Report titles
    'Transaction Report'                             => 'Informe de Transacciones',
    'Movements and Transactions Overview'            => 'Resumen de Movimientos y Transacciones',
    'All Transactions'                               => 'Todas las Transacciones',

    // Section headers
    'Period:'                                        => 'Período:',
    'Summary'                                        => 'Resumen',
    'Transactions'                                   => 'Transacciones',

    // Summary labels
    'Total Income'                                   => 'Total de Ingresos',
    'Total Expenses'                                 => 'Total de Gastos',
    'Expense'                                        => 'Gasto',
    'Net Balance'                                    => 'Saldo Neto',
    'Total Transactions'                             => 'Total de Transacciones',

    // Table headers
    'Date'                                           => 'Fecha',
    'Description'                                    => 'Descripción',
    'Category'                                       => 'Categoría',
    'Amount'                                         => 'Importe',
    'Type'                                           => 'Tipo',

    // Empty state
    'No transactions found for the selected period.' => 'No se encontraron transacciones para el período seleccionado.',

    // Transaction types
    'Income'                                         => 'Ingreso',
    'Expense'                                        => 'Gasto',
    'Transfer'                                       => 'Transferencia',

    // Header/Footer labels
    'Vessel:'                                        => 'Embarcación:',
    'Registration:'                                  => 'Registro:',
    'Type:'                                          => 'Tipo:',
    'Generated:'                                     => 'Generado:',
    'Generated by:'                                  => 'Generado por:',
    'Email:'                                         => 'Correo electrónico:',
    'Page :pageNumber of :pageCount'                 => 'Página :pageNumber de :pageCount',
    'Generated on'                                   => 'Generado el',
    'All rights reserved'                            => 'Todos los derechos reservados',

    // Marea Report
    'Marea Report'                                   => 'Informe de Marea',
    'Fishing Trip Overview'                          => 'Resumen de Viaje de Pesca',
    'Marea Information'                              => 'Información de la Marea',
    'Marea Number'                                   => 'Número de Marea',
    'Status'                                         => 'Estado',
    'Name'                                           => 'Nombre',
    'Dates'                                          => 'Fechas',
    'Estimated Departure'                            => 'Salida Estimada',
    'Actual Departure'                               => 'Salida Real',
    'Estimated Return'                               => 'Regreso Estimado',
    'Actual Return'                                  => 'Regreso Real',
    'Net Result'                                     => 'Resultado Neto',
    'Distribution Calculation'                       => 'Cálculo de Distribución',
    'Item'                                           => 'Item',
    'Value'                                          => 'Valor',
    'Final Result'                                   => 'Resultado Final',
    'Income Transactions'                            => 'Transacciones de Ingresos',
    'Expense Transactions'                           => 'Transacciones de Gastos',
    'Crew Members'                                   => 'Miembros de la Tripulación',
    'Crew Member'                                    => 'Miembro de la Tripulación',
    'Salary Payments'                                => 'Pagos de Salario',
    'Total Salary Payments'                          => 'Total de Pagos de Salario',
    'Fishing Quantity Returns'                       => 'Retornos de Cantidad de Pesca',

    // Maintenance Report
    'Maintenance Report'                             => 'Informe de Mantenimiento',
    'Maintenance Overview'                           => 'Resumen de Mantenimiento',
    'Maintenance Information'                        => 'Información de Mantenimiento',
    'Maintenance Number'                             => 'Número de Mantenimiento',
    'Start Date'                                     => 'Fecha de Inicio',
    'End Date'                                       => 'Fecha de Fin',
    'Closed At'                                      => 'Cerrado En',
    'Open'                                           => 'Abierto',
    'Closed'                                         => 'Cerrado',
    'Cancelled'                                      => 'Cancelado',
    'No transactions found for this maintenance.'    => 'No se encontraron transacciones para este mantenimiento.',
    'Quantity'                                       => 'Cantidad',
    'Notes'                                          => 'Notas',
    'transactions'                                   => 'transacciones',
    'Preparing'                                      => 'Preparando',
    'At Sea'                                         => 'En el Mar',
    'Returned'                                       => 'Regresado',
    'Closed'                                         => 'Cerrado',
    'Cancelled'                                      => 'Cancelado',

    // Financial Report
    'Financial Report'                               => 'Informe Financiero',
    'Comprehensive financial overview for'           => 'Resumen financiero integral para',
    'Category Breakdown'                             => 'Desglose por Categoría',
    'Expenses by Category'                           => 'Gastos por Categoría',
    'Income by Category'                             => 'Ingresos por Categoría',
    'Daily Breakdown'                                => 'Desglose Diario',
    'Mareas (Fishing Trips)'                         => 'Mareas (Viajes de Pesca)',
    'Percentage'                                     => 'Porcentaje',
    'Count'                                          => 'Cantidad',
    'Net'                                            => 'Neto',
    'Quantity Returns'                               => 'Retornos de Cantidad',
    'Uncategorized'                                  => 'Sin Categoría',
];
