<?php

return [
    // Report titles
    'Transaction Report'                             => 'Relatório de Transações',
    'Movements and Transactions Overview'            => 'Visão Geral de Movimentos e Transações',
    'All Transactions'                               => 'Todas as Transações',

    // Section headers
    'Period:'                                        => 'Período:',
    'Summary'                                        => 'Resumo',
    'Transactions'                                   => 'Transações',

    // Summary labels
    'Total Income'                                   => 'Total de Receitas',
    'Total Expenses'                                 => 'Total de Despesas',
    'Net Balance'                                    => 'Saldo Líquido',
    'Total Transactions'                             => 'Total de Transações',

    // Table headers
    'Date'                                           => 'Data',
    'Description'                                    => 'Descrição',
    'Category'                                       => 'Categoria',
    'Amount'                                         => 'Valor',
    'Type'                                           => 'Tipo',

    // Empty state
    'No transactions found for the selected period.' => 'Nenhuma transação encontrada para o período selecionado.',

    // Transaction types
    'Income'                                         => 'Receita',
    'Expense'                                        => 'Despesa',
    'Transfer'                                       => 'Transferência',

    // Header/Footer labels
    'Vessel:'                                        => 'Embarcação:',
    'Registration:'                                  => 'Registo:',
    'Type:'                                          => 'Tipo:',
    'Generated:'                                     => 'Gerado:',
    'Generated by:'                                  => 'Gerado por:',
    'Email:'                                         => 'E-mail:',
    'Page :pageNumber of :pageCount'                 => 'Página :pageNumber de :pageCount',
    'Generated on'                                   => 'Gerado em',
    'All rights reserved'                            => 'Todos os direitos reservados',
];
