<?php

return [
    // Report titles
    'Transaction Report'                             => 'Relatório de Transações',
    'Movements and Transactions Overview'            => 'Visão Geral de Movimentos e Transações',
    'All Transactions'                               => 'Todas as Transações',

    // Section headers
    'Period:'                                        => 'Período:',
    'Summary'                                        => 'Resumo',
    'Transactions'                                   => 'Transações',

    // Summary labels
    'Total Income'                                   => 'Total de Receitas',
    'Total Expenses'                                 => 'Total de Despesas',
    'Net Balance'                                    => 'Saldo Líquido',
    'Total Transactions'                             => 'Total de Transações',

    // Table headers
    'Date'                                           => 'Data',
    'Description'                                    => 'Descrição',
    'Category'                                       => 'Categoria',
    'Amount'                                         => 'Valor',
    'Type'                                           => 'Tipo',

    // Empty state
    'No transactions found for the selected period.' => 'Nenhuma transação encontrada para o período selecionado.',

    // Transaction types
    'Income'                                         => 'Receita',
    'Expense'                                        => 'Despesa',
    'Transfer'                                       => 'Transferência',

    // Header/Footer labels
    'Vessel:'                                        => 'Embarcação:',
    'Registration:'                                  => 'Registo:',
    'Type:'                                          => 'Tipo:',
    'Generated:'                                     => 'Gerado:',
    'Generated by:'                                  => 'Gerado por:',
    'Email:'                                         => 'E-mail:',
    'Page :pageNumber of :pageCount'                 => 'Página :pageNumber de :pageCount',
    'Generated on'                                   => 'Gerado em',
    'All rights reserved'                            => 'Todos os direitos reservados',

    // Marea Report
    'Marea Report'                                   => 'Relatório de Marea',
    'Fishing Trip Overview'                          => 'Visão Geral da Viagem de Pesca',
    'Marea Information'                              => 'Informações da Marea',
    'Marea Number'                                   => 'Número da Marea',
    'Status'                                         => 'Estado',
    'Name'                                           => 'Nome',
    'Dates'                                          => 'Datas',
    'Estimated Departure'                            => 'Partida Estimada',
    'Actual Departure'                               => 'Partida Real',
    'Estimated Return'                               => 'Retorno Estimado',
    'Actual Return'                                  => 'Retorno Real',
    'Net Result'                                     => 'Resultado Líquido',
    'Distribution Calculation'                       => 'Cálculo de Distribuição',
    'Item'                                           => 'Item',
    'Value'                                          => 'Valor',
    'Final Result'                                   => 'Resultado Final',
    'Income Transactions'                            => 'Transações de Receita',
    'Expense Transactions'                           => 'Transações de Despesa',
    'Crew Members'                                   => 'Membros da Tripulação',
    'Crew Member'                                    => 'Membro da Tripulação',
    'Salary Payments'                                => 'Pagamentos de Salário',
    'Total Salary Payments'                          => 'Total de Pagamentos de Salário',
    'Fishing Quantity Returns'                       => 'Retornos de Quantidade de Pesca',
    'Quantity'                                       => 'Quantidade',
    'Notes'                                          => 'Notas',
    'transactions'                                   => 'transações',
    'Preparing'                                      => 'Preparando',
    'At Sea'                                         => 'No Mar',
    'Returned'                                       => 'Retornado',
    'Closed'                                         => 'Fechado',
    'Cancelled'                                      => 'Cancelado',
];
