<?php

return [
    // Report titles
    'Transaction Report'                             => 'Relatório de Transações',
    'Movements and Transactions Overview'            => 'Visão Geral de Movimentos e Transações',
    'All Transactions'                               => 'Todas as Transações',

    // Section headers
    'Period:'                                        => 'Período:',
    'Summary'                                        => 'Resumo',
    'Transactions'                                   => 'Movimentações',

    // Summary labels
    'Total Income'                                   => 'Total de Receitas',
    'Total Expenses'                                 => 'Total de Despesas',
    'Expense'                                        => 'Despesa',
    'Net Balance'                                    => 'Saldo Líquido',
    'Total Transactions'                             => 'Total de Movimentações',

    // Table headers
    'Date'                                           => 'Data',
    'Description'                                    => 'Descrição',
    'Category'                                       => 'Categoria',
    'Amount'                                         => 'Valor',
    'Type'                                           => 'Tipo',

    // Empty state
    'No transactions found for the selected period.' => 'Nenhuma transação encontrada para o período selecionado.',

    // Transaction types
    'Income'                                         => 'Receita',
    'Expense'                                        => 'Despesa',
    'Transfer'                                       => 'Transferência',

    // Header/Footer labels
    'Vessel:'                                        => 'Embarcação:',
    'Registration:'                                  => 'Registo:',
    'Type:'                                          => 'Tipo:',
    'Generated:'                                     => 'Gerado:',
    'Generated by:'                                  => 'Gerado por:',
    'Email:'                                         => 'E-mail:',
    'Page :pageNumber of :pageCount'                 => 'Página :pageNumber de :pageCount',
    'Generated on'                                   => 'Gerado em',
    'All rights reserved'                            => 'Todos os direitos reservados',

    // Marea Report
    'Marea Report'                                   => 'Relatório de Marea',
    'Fishing Trip Overview'                          => 'Visão Geral da Viagem de Pesca',
    'Marea Information'                              => 'Informações da Marea',
    'Marea Number'                                   => 'Número da Marea',
    'Status'                                         => 'Estado',
    'Name'                                           => 'Nome',
    'Dates'                                          => 'Datas',
    'Estimated Departure'                            => 'Partida Estimada',
    'Actual Departure'                               => 'Partida Real',
    'Estimated Return'                               => 'Retorno Estimado',
    'Actual Return'                                  => 'Retorno Real',
    'Net Result'                                     => 'Resultado Líquido',
    'Distribution Calculation'                       => 'Cálculo de Distribuição',
    'Item'                                           => 'Item',
    'Value'                                          => 'Valor',
    'Final Result'                                   => 'Resultado Final',
    'Income Transactions'                            => 'Movimentações de Receita',
    'Expense Transactions'                           => 'Movimentações de Despesa',
    'Crew Members'                                   => 'Membros da Tripulação',
    'Crew Member'                                    => 'Membro da Tripulação',
    'Salary Payments'                                => 'Pagamentos de Salário',
    'Total Salary Payments'                          => 'Total de Pagamentos de Salário',
    'Fishing Quantity Returns'                       => 'Retornos de Quantidade de Pesca',

    // Maintenance Report
    'Maintenance Report'                             => 'Relatório de Manutenção',
    'Maintenance Overview'                           => 'Visão Geral da Manutenção',
    'Maintenance Information'                        => 'Informações da Manutenção',
    'Maintenance Number'                             => 'Número da Manutenção',
    'Start Date'                                     => 'Data de Início',
    'End Date'                                       => 'Data de Fim',
    'Closed At'                                      => 'Fechado Em',
    'Open'                                           => 'Aberto',
    'Closed'                                         => 'Fechado',
    'Cancelled'                                      => 'Cancelado',
    'No transactions found for this maintenance.'    => 'Nenhuma transação encontrada para esta manutenção.',
    'Quantity'                                       => 'Quantidade',
    'Notes'                                          => 'Notas',
    'transactions'                                   => 'transações',
    'Preparing'                                      => 'Preparando',
    'At Sea'                                         => 'No Mar',
    'Returned'                                       => 'Retornado',
    'Closed'                                         => 'Fechado',
    'Cancelled'                                      => 'Cancelado',

    // Financial Report
    'Financial Report'                               => 'Relatório Financeiro',
    'Comprehensive financial overview for'           => 'Visão geral financeira abrangente para',
    'Category Breakdown'                             => 'Resumo por Categoria',
    'Expenses by Category'                           => 'Despesas por Categoria',
    'Income by Category'                             => 'Receitas por Categoria',
    'Daily Breakdown'                                => 'Resumo Diário',
    'Mareas (Fishing Trips)'                         => 'Mareas (Viagens de Pesca)',
    'Percentage'                                     => 'Percentagem',
    'Count'                                          => 'Contagem',
    'Net'                                            => 'Líquido',
    'Quantity Returns'                               => 'Retornos de Quantidade',
    'Uncategorized'                                  => 'Sem Categoria',

    // VAT Report
    'VAT Report'                                     => 'Relatório de IVA',
    'Comprehensive VAT overview for'                 => 'Visão geral completa do IVA para',
    'Total VAT'                                      => 'Total de IVA',
    'Base Amount'                                    => 'Valor Base',
    'Total with VAT'                                 => 'Total com IVA',
    'VAT by Profile'                                 => 'IVA por Perfil',
    'VAT by Category'                                => 'IVA por Categoria',
    'Daily VAT Breakdown'                            => 'Análise Diária de IVA',
    'VAT by Marea'                                   => 'IVA por Marea',
    'All Transactions with VAT'                      => 'Todas as Movimentações com IVA',
    'VAT Profile'                                    => 'Perfil de IVA',
    'VAT'                                            => 'IVA',
    'Total'                                          => 'Total',
    'Unknown'                                        => 'Desconhecido',
];
